### PR TITLE
Flight plan overlay

### PR DESCRIPTION
**Pull request by dave6502**
Phase 2 - load (VFR style) FMS files in Route App. No procedures (SIDs, STARs etc.) handled yet.
I will email you some test FMS files.

### CODE REVIEW

**Review by fpw — APPROVED** [review]
Looks good to me, thanks for doing this in multiple PRs so I can review it easier.
There's a tiny merge conflice in .gitignore. @cyberang3l is planning to do a bigger PR as well and changed the .gitignore in preparation of that, but it's otherwise unrelated to your changes. He's going to add support for a new map source that allows external configuration of map server URLs so users can add new sources themselves.

**Comment by mjh65** [comment]
I discussed this with @dave6502, and suggested that it would be helpful if the FMS loader and parser classes were moved into the world namespace and library so that they will also be available to the MSFS variant of Avitab (which is currently still in development in my fork).

I have made these changes in my repo, and can submit an alternative PR (also with the merge conflict resolved). Or if this change will be merged imminently then I will submit a later PR to move the FMS classes into a simulator-agnostic location.

**Comment by fpw** [comment]
@mjh65 If you already have these changes in your repo, making an alternative PR sounds good.

**Comment by fpw** [comment]
Included in #173

**Pull request closed without merging**
