### PR TITLE
Configurable online slippy maps 3

### PR DESCRIPTION
**Pull request by cyberang3l**
Enable the remaining features for the online maps

* Multiple tile servers are now supported in the mapconfig.json. The
  default mapconfig.json has been updated to reflect these changes.
* The url is now parsed correctly and used by the OpenTopoSource class
* The min/max zoom levels are also properly parsed and used by the
  OpenTopoSource class
* Added more sanity and validation checks to reduce failing in cases
  where users add leading or trailing slashes to the servers and/or
  urls. Part of the validation checks are better error messages to
  help users root cause mistakes in the configuration of newly added
  maps

After this diff the support for used-defined online maps is mostly "feature-complete".
Some things that are left to be done, but probably not so urgent:
* Introduce two more json config params for `tile_width` and `tile_height`.
  I think openflightmaps uses 512x512 tiles, so this would be useful, and
  it would be pretty straight forward to add (:crossed_fingers:) - **Update**:
  This was indeed trivial, and can be found in the PR #168 
* Rename the `OpenTopoSource` filenames and class to something more
  generic like `SlippyMapSource` or `OnlineMapSource`?
* If a map from the custom online maps is enabled, store it's name in a variable
  and add it to the description beside the "Online" button as a hint to the user to
  know which custom map is currently in use? I was thinking this will be nice. E.g.,
  if the OpenTopoMap is enabled, the next time the user clicks the map settings,
  instead of seeing only the description "Select slippy tiles from online sources",
  we could show a second line "Currently active map: OpenTopoMap" (change
  OpenTopoMap with actual map name that is enabled)
* Get rid of the Stamen and OpenTopo buttons and move these maps under the
  "Online" button. Then move the "Online" button to the top of the list.
* Update the wiki with some documentation? The behaviour is mostly documented
  in this commit message: https://github.com/fpw/avitab/commit/f9128d1015dde1c37fd5908001c63e3de70b94a9

### CODE REVIEW

**Comment by fpw** [comment]
Going forward, I suggest `OnlineSlippySource` as new class name since that reflects the name of its config class.

**Comment by cyberang3l** [comment]
_Rename the OpenTopoSource filenames and class to something more generic like SlippyMapSource or OnlineMapSource?_ <- This is done in #170 

_If a map from the custom online maps is enabled, store it's name in a variable
and add it to the description beside the "Online" button...._ <- this is done in #172

Now about this: _Get rid of the Stamen and OpenTopo buttons and move these maps under the
"Online" button. Then move the "Online" button to the top of the list._, I was wondering how to implement this correctly.

Ideally, we want to have OpenTopoMaps as a fixed, hard-coded configuration so that in case a user messes up their mapconfig.json, can still, at least access OpenTopoMaps.

So I was rethinking about this... and maybe we should leave the OpenTopoMaps button in place, and only move Stamen maps in the `mapconfig.json` and remove the "Stamen" button? What do you think @fpw ?

By the way, the Stamen maps don't even work for me. So if we want to make this change, is it something you can do as I cannot even test it myself? If you agree on this, then I think I'm already done with the feature implementation.

**Comment by fpw** [comment]
> maybe we should leave the OpenTopoMaps button in place, and only move Stamen maps in the `mapconfig.json` and remove the "Stamen" button? What do you think @fpw ?

I think having all online sources in the JSON is fine. If OpenTopo gets messed up, it must be because the user changed the JSON file - which means they know how to edit or potentially restore it. This will leave more place in the menu for the various Navigraph map buttons.

> Stamen doesn't work.

It seems they[ no longer host a free tile server](https://maps.stamen.com/stadia-partnership/), so it can be removed completely. On the other hand, I think OpenStreetMap's policy now allows tools like AviTab, so that can be enabled by default instead.

**Comment by cyberang3l** [comment]
OK, then I'll proceed like we initially planned.

Remove both OpenTopo and Stamen buttons. Move the "Online" button at the top of the menu, and enable OpenTopoMap by default. I'll remove completely the Stamen topo source.

You'll get the last PR soon then :)

**Pull request merged**
